spring.application.name=emissionen_rechner

spring.datasource.url=jdbc:postgresql://localhost:5432/_vibe_2526
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=geheim123

spring.jpa.hibernate.ddl-auto=create

#docker run -p 5432:5432 -d --name postgres --network pos-syp -e POSTGRES_PASSWORD=password